linters:
    StringQuotes:
        enabled: true
        style: double_quotes

    SelectorDepth:
        enabled: true
        max_depth: 4

    NestingDepth:
        enabled: true
        max_depth: 4
        ignore_parent_selectors: false
